In [1]:
import numpy as np
calls=np.array([5,7,8,9,11])
print(calls)


[ 5  7  8  9 11]


Multi dimentional Array

In [ ]:
dimentional=np.array((['jan','feb','mar'],
                    [300,400,500],
                    [600,700,800],
                    [50,30,200]))
print(dimentional.shape)
print(dimentional)

(4, 3)
[['jan' 'feb' 'mar']
 ['300' '400' '500']
 ['600' '700' '800']
 ['50' '30' '200']]


In [ ]:
mc=np.array((['jan','feb','mar'],
                    [300,400,500],
                    [600,700,800],
                    [50,30,200]))
print(mc[1,:])
print(mc[:,1])
print(mc[1:,2])
print(mc[1:,1])
print(mc[1:,0])
print(mc[3:,])


['300' '400' '500']
['feb' '400' '700' '30']
['500' '800' '200']
['400' '700' '30']
['300' '600' '50']
[['50' '30' '200']]


In [27]:
#satisfaction rating
sr=np.array([3.6,4,2,3,7,9])
print(sr[sr>3])
print(sr)
print(sr[(sr>=2) & (sr<=4)])

[3.6 4.  7.  9. ]
[3.6 4.  2.  3.  7.  9. ]
[3.6 4.  2.  3. ]


In [36]:
mc=np.array((['jan','feb','mar'],
                    [300,400,500],
                    [600,700,800],
                    [50,30,200]))
print(np.sum(mc[1:].astype(int)))

3580


In [39]:
mc=np.array((['jan','feb','mar'],
                    [300,400,500],
                    [600,700,800],
                    [50,30,200]))
print(np.mean(mc[1:].astype(int)))
print(np.min(mc[1:].astype(int)))
print(np.max(mc[1:].astype(int)))

397.77777777777777
30
800


In [43]:
north=np.array([5,100,30])
south=np.array([3,2,5])
print(np.concatenate((north,south)))


[  5 100  30   3   2   5]


In [50]:
mc=np.array((['jan','feb','mar'],
                    [300,400,500],
                    [600,700,800],
                    [50,30,200]))
print(mc[1:,])
calls=mc[1:,].astype(int)
print(np.add.reduce(calls,axis=0))

[['300' '400' '500']
 ['600' '700' '800']
 ['50' '30' '200']]
[ 950 1130 1500]


In [59]:
import numpy as np

mc = np.array([
    ['jan', 'feb', 'mar'],
    [300, 400, 500],
    [600, 700, 800],
    [50, 30, 200]
])

result = np.sum(mc[1:].astype(int), axis=0)
print(result)

[ 950 1130 1500]
